name: noahdanielhayes
favicon: null
layout_spectrum: 0.5982686672359705
typography_spectrum: 0.7779384020250291
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.1268040610011667
  lightness: 0.4277074309065938
  saturation: 0.5354457157664001
  rhythmicContrast: 0.9369491895195097
purpose: []
